version: '1'

networks: 
  transaction-network:
      driver: bridge

services:
  dotnet:
    image: dotnetapp
    build:
      context: .
    ports:
     - "80:80"
     - "443:443"
    networks:
      - transaction-network
    volumes:
     - ./www:/var/www/html
    links:
     - db
  db:
    image: mysql:5.7
    volumes:
     - /var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=phprs
     - MYSQL_DATABASE=phprs

  # siteheroismarvel:
  #   image: siteheroismarvel
  #   build:
  #     context: .
  #   ports:
  #     - "20000:80"
  #   networks:
  #     - marvel-network
  #   depends_on:
  #     - "redisheroismarvel"

  # redisheroismarvel:
  #   image: redis:alpine
  #   ports:
  #     - "16379:6379"
  #   networks:
  #     - marvel-network

# version: '3.4'

# networks: 
#     - transaction

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        # networks: 
        #     - transaction-network
        ports:
            - '8080:80'
        links: 
            - db
    db:
        image: mysql:5.7
        # ports:
        #     - '3307:3306'
        # networks: 
        #     - transaction-network
        volumes:
            - /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=transactions