version: '3.4'

networks: 
    transaction:
        driver: bridge

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        networks: 
            - transaction
        ports:
            - '8080:80'
        links: 
            - db
    db:
        image: mysql:5.7
        ports:
            - '3307:3306'
        networks: 
            - transaction
        volumes:
            - /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=toor123
            - MYSQL_DATABASE=transactions