// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transactions.Data;

namespace Transactions.Migrations
{
    [DbContext(typeof(TransactionsContext))]
    [Migration("20201224042749_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Transactions.Models.Bank", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Transactions.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BanckDestinationid")
                        .HasColumnType("int");

                    b.Property<int?>("BanckOriginid")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("TransactionTypeid")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.HasIndex("BanckDestinationid");

                    b.HasIndex("BanckOriginid");

                    b.HasIndex("TransactionTypeid");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Transactions.Models.TransactionType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("Transactions.Models.Transaction", b =>
                {
                    b.HasOne("Transactions.Models.Bank", "BanckDestination")
                        .WithMany()
                        .HasForeignKey("BanckDestinationid");

                    b.HasOne("Transactions.Models.Bank", "BanckOrigin")
                        .WithMany()
                        .HasForeignKey("BanckOriginid");

                    b.HasOne("Transactions.Models.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeid");
                });
#pragma warning restore 612, 618
        }
    }
}
